# source: https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb

IMAGENET_TEMPLATES = [
    "a bad photo of a {}.",
    "a photo of many {}.",
    "a sculpture of a {}.",
    "a photo of the hard to see {}.",
    "a low resolution photo of the {}.",
    "a rendering of a {}.",
    "graffiti of a {}.",
    "a bad photo of the {}.",
    "a cropped photo of the {}.",
    "a tattoo of a {}.",
    "the embroidered {}.",
    "a photo of a hard to see {}.",
    "a bright photo of a {}.",
    "a photo of a clean {}.",
    "a photo of a dirty {}.",
    "a dark photo of the {}.",
    "a drawing of a {}.",
    "a photo of my {}.",
    "the plastic {}.",
    "a photo of the cool {}.",
    "a close-up photo of a {}.",
    "a black and white photo of the {}.",
    "a painting of the {}.",
    "a painting of a {}.",
    "a pixelated photo of the {}.",
    "a sculpture of the {}.",
    "a bright photo of the {}.",
    "a cropped photo of a {}.",
    "a plastic {}.",
    "a photo of the dirty {}.",
    "a jpeg corrupted photo of a {}.",
    "a blurry photo of the {}.",
    "a photo of the {}.",
    "a good photo of the {}.",
    "a rendering of the {}.",
    "a {} in a video game.",
    "a photo of one {}.",
    "a doodle of a {}.",
    "a close-up photo of the {}.",
    "a photo of a {}.",
    "the origami {}.",
    "the {} in a video game.",
    "a sketch of a {}.",
    "a doodle of the {}.",
    "a origami {}.",
    "a low resolution photo of a {}.",
    "the toy {}.",
    "a rendition of the {}.",
    "a photo of the clean {}.",
    "a photo of a large {}.",
    "a rendition of a {}.",
    "a photo of a nice {}.",
    "a photo of a weird {}.",
    "a blurry photo of a {}.",
    "a cartoon {}.",
    "art of a {}.",
    "a sketch of the {}.",
    "a embroidered {}.",
    "a pixelated photo of a {}.",
    "itap of the {}.",
    "a jpeg corrupted photo of the {}.",
    "a good photo of a {}.",
    "a plushie {}.",
    "a photo of the nice {}.",
    "a photo of the small {}.",
    "a photo of the weird {}.",
    "the cartoon {}.",
    "art of the {}.",
    "a drawing of the {}.",
    "a photo of the large {}.",
    "a black and white photo of a {}.",
    "the plushie {}.",
    "a dark photo of a {}.",
    "itap of a {}.",
    "graffiti of the {}.",
    "a toy {}.",
    "itap of my {}.",
    "a photo of a cool {}.",
    "a photo of a small {}.",
    "a tattoo of the {}.",
]

PARAPHRASED_TEMPLATES = [
    "An unclear image of a {}.",
    "A picture showing multiple {}.",
    "A detailed carving of a {}.",
    "An image where the {} is barely visible.",
    "A grainy snapshot of the {}.",
    "A computer-generated image of a {}.",
    "Street art representing a {}.",
    "A low-quality image of the {}.",
    "A partially cropped view of a {}.",
    "A permanent ink sketch of a {}.",
    "The stitched pattern of a {}.",
    "An image where spotting the {} is tricky.",
    "A vibrant and well-lit photo of a {}.",
    "An image of a spotless and tidy {}.",
    "A photograph of an unclean {}.",
    "A shadowy picture featuring the {}.",
    "A hand-drawn sketch of a {}.",
    "This is my {} captured in an image.",
    "A toy version of a {}.",
    "A stylish representation of the {}.",
    "A zoomed-in shot of a {}.",
    "An artistic illustration of the {}.",
    "An oil painting showcasing a {}.",
    "A blurred and pixelated view of the {}.",
    "A handmade sculpture of the {}.",
    "A glowing and colorful shot of a {}.",
    "A toy figurine resembling a {}.",
    "An unusual and quirky image of a {}.",
    "A fuzzy snapshot of a {}.",
    "A cartoon-style drawing of a {}.",
    "A creative digital rendering of the {}.",
    "A carefully embroidered piece showing a {}.",
    "An experimental filter applied to a photo of a {}.",
    "An impressive, high-quality picture of the {}.",
    "A realistic depiction of a {} in a game.",
    "A humorous doodle of the {}.",
    "A fancy origami shaped like a {}.",
    "A compact and cute view of the {}.",
    "A luxurious and shiny version of a {}.",
    "A spooky and dark shot of the {}.",
    "A poster design inspired by the {}.",
    "A colorful tattoo featuring a {}.",
    "A modern graphic showing the {}.",
    "An artsy, vintage-style photo of a {}.",
    "A quick pencil sketch of the {}.",
    "A creative rendition of a {} in VR.",
    "A bright and happy depiction of a {}.",
    "A cool sticker design inspired by a {}.",
    "A black-and-white photo of a {}.",
    "A playful toy designed as a {}."
]

IMAGENET_TEMPLATES_SELECT = [
    "itap of a {}.",
    "a bad photo of the {}.",
    "a origami {}.",
    "a photo of the large {}.",
    "a {} in a video game.",
    "art of the {}.",
    "a photo of the small {}.",
]
